---
title: "HW3"
description: Wrangling Australian Marriage Data
  A new article created using the Distill format.
author:
  - name: Nathaniel Ross
    url: https://github.com/njrossUMass/DACSS601August2021
    affiliation: UMass DACSS
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(readxl)
```

```{r, include =TRUE}
#Reading in my data on marriage
Aus_Marriage <- read_csv("_data/australian_marriage_tidy.csv")

```
```{r, include = TRUE}
#dimension for my data set
dim(Aus_Marriage)
#Getting column names for my data set
colnames(Aus_Marriage)


```
In my data set on Australian marriages there are 16 rows and 4 columns with variable names indicating Australian Territory name, Response(Y/N), the count of a particular response, and the percent of territory with that specific response

```{r, include = TRUE}
#I am selecting my data by territory, response, percent, and then arranging my data in descending order by percent
Aus_Marriage %>%
select(territory, resp, percent) %>%
  arrange(desc(percent)) %>%
  filter(resp == 'yes')
  
summarize(Aus_Marriage, 'territory', 'resp', 'percent')
  

  
```

